CREATE TABLE PERSON(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(255) NOT NULL,
  LAST_NAME VARCHAR(255) NOT NULL,
  AGE INTEGER NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE ADDRESS(
    ID_ADDRESS BIGINT NOT NULL AUTO_INCREMENT,
    STREET VARCHAR(255) NOT NULL,
    STREET_NR INTEGER NOT NULL,
    ZIP_CODE INTEGER NOT NULL,
    PRIMARY KEY (ID_ADDRESS)
);